export const Velocity = require("velocity-animate/velocity.js");
require("velocity-animate/velocity.ui.js");
import Vue from "vue";
import {
  Button,
  Container,
  Header,
  Main,
  Aside,
  Footer,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Image,
  Autocomplete,
  Input,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Row,
  Col,
  Select,
  Option,
  Avatar,
  Popover,
  Breadcrumb,
  BreadcrumbItem,
  Progress,
  ButtonGroup,
  Table,
  TableColumn,
  RadioGroup,
  RadioButton,
  InputNumber,
} from "element-ui";

Vue.use(InputNumber);
Vue.use(RadioGroup);
Vue.use(RadioButton);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(ButtonGroup);
Vue.use(Progress);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Popover);
Vue.use(Option);
Vue.use(Avatar);
Vue.use(Select);
Vue.use(Row);
Vue.use(Col);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Autocomplete);
Vue.use(Input);
Vue.use(Button);
Vue.use(Container);
Vue.use(Header);
Vue.use(Main);
Vue.use(Footer);
Vue.use(Aside);
Vue.use(MenuItemGroup);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Image);
